version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coveralls
    versions:
    - "> 3.0.9, < 3.1"
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: ts-loader
    versions:
    - 8.0.13
    - 8.0.14
  - dependency-name: "@types/webpack-manifest-plugin"
    versions:
    - 3.0.1
  - dependency-name: css-loader
    versions:
    - 5.0.1
